language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# Command to install dependencies
install:
  - pip install -U setuptools
  - pip install -U numpy
  - pip install -U pytest
  - pip install .[test,doc]
  - pip install codecov

# Command to run tests
script:
  - pytest
  # Install pandoc (to convert notebooks to html)
  - apt-get update -y
  - apt-get install -y pandoc
  - cd doc
  - make html

# Command to push coverage to codecov
after_success:
  - codecov -t 55a7aa09-3763-45cf-ad06-df0f26f5168c
