language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install -U numpy
  - pip install -U pytest
  - pip install .[test,doc]
  - pip install codecov
# command to run tests
script:
  - pytest
after_success:
  - codecov -t 55a7aa09-3763-45cf-ad06-df0f26f5168c
